# .github/workflows/cvent-abandoned.yml

name: Cvent Abandoned Registrations Sync

on:
  repository_dispatch:
    types: [run-cvent-abandoned]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: It worked
        run: echo "Webhook received and workflow triggered successfully"
